

TESTS =  \
	AltBlckQ  \
	AltPollQ  

all: AltBlckQ AltPollQ
	echo "doit"

AltBlckQ:
	echo "yolo"


AltPollQ:
	echo "tata"

#    blocktim  countsem  dead     EventGroupsDemo  flop      integer   PollQ  QueueOverwrite  QueueSetPolling  semtest  TaskNotify  xxx
#AltBlock  AltQTest  BlockQ  Common    crhook    dynamic  failing          GenQTest  Makefile  QPeek  QueueSet        recmutex         sp_flop  test1

